var keywords = [
	"sang saigné",
	"beaucoup",
	"petite",
	"grosse",
	"plaie",
	"accident,blaissé",
	"inconscient",
	"comment",
	"secours",
	"numéro",
	"quoi",
	"brulure,brulé",
	"aide",
	"danger",
	"douleur",
	"mal",
	"respire,respirer,respiré",
	"pas",
	"etouffe,etouffé",
	"perdu,(connaissance)",
	"hopital",
	"urgent",
	"vite",
	"electricité",
	"outils,perceuse scie marteau",
	"tombé,tombe,chute,chuté",
	"haut",
	"eau",
	"medicament",
	"parler",
	"intoxiquation,intoxiqué, poison"
];


var answers = [
	"Si il y beaucoup de sang, appuyez sur la plaie et appelez à l'aide et le 15 (secours)", 
	"Si la la plait est petite, netoyé avec de l'eau et du savon, desinfecté (si possible) puis appliqué bandage (si vraiment petite, pas la peine)", 
	"Si la personne est inconsciente, commencer par vérifier si il respire puis mettez le en position latérale de sécurité (PLS). Appelez immédiatement les secours (15)",
	"Débrancher l'outil, écarté le puis verifier si la victime est consciente.",
	"Trouver le compteur électrique et eteigner le. Ecarté l'outil et vérifier si la victime est consciente.",
	"Passer de l'eau sur la brulure pendant au moins 5 minutes. Protégé la brulure sans pour autant la serré ou y coler quelque chose dessus(parachute)",
	"Passer de l'eau sur la brulure et appelez les secours (le 15). Laissé couler doucement l'eau froide jusqu'a l'arrivé des secours",
	"Pour vérifier si une personne est inconsciente, demandez lui d'ouvrir les yeux, de vous serez les mains. Aucune réponse veux dire qu'elle est inconsciente",
	"La personne a du mal a respirer mais peut parler (produire un son). Asseyez la contre un mur ou une chaisse et appelé les secours (15). Attention, il est important de ne pas lui taper dans le dos pour éviter d'agraver la situation",
	"La victime ne peut ni parler, ni respirer, ni tousser. Elle peut émettre des sifflements ou tenter de tousser sans émettre de bruit: Donnez un maximum de 5 claques dans le dos de la victime. Après chaque claque, vérifiez si tout rentre dans l'ordre. Si les claques dans le dos n'ont pas d'effet, effectuez un maximum de 5 compressions abdominales. Si n'y a toujours pas d'amélioration, appeler les secours (15). Si la personne perd connaissance, posez la délicatement au sol et alertez immédiamente les secours (15)",
	"Si la personne a perdu connaissance, posez-la délicatement au sol (si besoin), verifier sa respiration. Si elle respire alertez immédiatement les secours",
	"Si la personne a perdu connaissance, posez-la délicatement au sol (si besoin), verifier sa respiration. SI elle ne respire pas, vérifier sont poue et allertez immédiatement les secours. Pratiquer une réanimation cardio-pulmonaire unique si il n'y ni poue, ni respiration.",
	"Si la personne à été électrifié, chercher toutes sources électriques dangeureuse et neutralisé la (éteindre compteur électrique, débranché appareil), chercher les points de contact et traité la comme pour une brulure. Appelez ensuite les secours (15)",
	"Si une personne est tombé de haut, et est toujours consciente, demander lui de ne pas bouger et ne la toucher pas. Appelez immédiatement les secours (15)",
	"Si la personne est tombé de haut et est inconsciente, Ne la toucher pas mais vérifier sa respiration et sont poue. Appelez immédiatement les secours (15) et procédé à une réanimation cardio-pulmonaire si nécessaire (pas de poue ni de respiration). Le numéro des secours est le 15",
	"Si la personne a ingéré le mauvais médicament (pas le bon traitement), appelez immédiatement les secours (15)",
];

var dataset = [
	[0, 1, 4, 12, 0],
	[2, 4, 1],
	[6, 7, 19, 2],
	[23, 24, 9, 12, 5, 3],
	[23, 24, 27, 5, 4],
	[11, 2, 5],
	[11, 3, 6],
	[6, 7, 12, 7],
	[16, 17, 18, 8],
	[16, 17, 18, 1, 21, 29, 9],
	[19, 10],
	[19, 11],
	[23, 7, 10, 12],
	[26, 25, 13],
	[26, 25, 19, 6, 14],
	[28, 30,  15],
]